# Image enhancement
ENHANCE_CACHE_MAX = 4
AUTOCONTRAST_CUTOFF = 0.5

BLOOD_COLOR_BOOST = 1.8
BLOOD_CONTRAST_BOOST = 1.4
BLOOD_UNSHARP = dict(radius=2, percent=150, threshold=3)

TISSUE_CONTRAST_BOOST = 1.2
TISSUE_SHARPNESS_BOOST = 1.3

SKIN_CONTRAST_BOOST = 1.5
SKIN_UNSHARP = dict(radius=2, percent=200, threshold=2)
SKIN_EDGE_AUTOCONTRAST_CUTOFF = 1

DEFAULT_SHARPNESS_BOOST = 1.5

# Image quality thresholds
BLUR_EDGE_VAR_MIN = 20
UNDEREXPOSED_MEAN_MAX = 40
OVEREXPOSED_MEAN_MIN = 240
GRAYSCALE_RB_DIFF_MAX = 5

# Inference
MAX_NEW_TOKENS = 600
MAX_NEW_TOKENS_OOM_RETRY = 400
GEN_RETRY_SLEEP_SEC = 1
MODEL_ID = "google/medgemma-4b-it"

# Upload limits
MAX_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_PIXELS = 25_000_000
THUMBNAIL_MAX = (4096, 4096)

# Debug
DEBUG_LOG_MAX = 50
DEBUG_DATA_TRUNCATE = 2000
